spring.application.name=Client
# Application Name

# Admin server will run on this port
server.port=8081

# Register this service with Spring Boot Admin
spring.boot.admin.client.url=http://localhost:8080


# Show all actuator endpoints in UI
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.server.port=8081
server.address=0.0.0.0